astroplotter/astroplotter/urls.py
from django.contrib import admin
from django.urls import path, include
from data_reader.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('data-reader/', include('data_reader.urls')),
    path('cmd-plotter/', include('cmd_plotter.urls')),
    path('imf-plotter/', include('imf_plotter.urls')),
    path('', home, name='home'),
]

astroplotter/cmd_plotter/urls.py
# cmd_plotter/urls.py

from django.urls import path
from .views import plot_cmd

app_name = 'cmd_plotter'

urlpatterns = [
    path('plot-cmd/', plot_cmd, name='plot_cmd'),
    
]

astroplotter/imf_plotter/urls.py
from django.urls import path
from .views import imf_plot, data_download

app_name = 'imf_plotter'

urlpatterns = [
    path('', imf_plot, name='imf_plot'),
    path('download/', data_download, name='data_download'),
]

astroplotter/imf_plotter/models.py
from django.db import models

# Create your models here.

astroplotter/imf_plotter/forms.py
from django import forms
from data_reader.models import UploadedFile, FileColumn
import pandas as pd

class IMFPlotForm(forms.Form):
    uploaded_file = forms.ModelChoiceField(queryset=UploadedFile.objects.all(), label="Select File")
    mass_column = forms.ChoiceField(label="Select the 'mass column'", required=True)
    log_scale = forms.BooleanField(label="Data is in logartihmic scale", required=False)
    def __init__(self, *args, **kwargs):
        uploaded_files = kwargs.pop('uploaded_files', None)
        super().__init__(*args, **kwargs)
        
        if uploaded_files:
            self.fields['uploaded_file'].queryset = uploaded_files

        if 'uploaded_file' in self.data:
            try:
                file_id = int(self.data.get('uploaded_file'))
                self.fields['mass_column'].choices = self.get_column_choices(file_id)
            except (ValueError, TypeError) as e:
                print(f"Debug: Exception in form init: {e}")

    def get_column_choices(self, file_id):
        columns = FileColumn.objects.filter(file_id=file_id).values_list('column_name', 'column_name')
        return list(columns)

astroplotter/imf_plotter/views.py
# imf_plotter/views.py
from django.shortcuts import render
from django.http import HttpResponse
import csv
from .forms import IMFPlotForm
import plotly.graph_objects as go
import pandas as pd
import numpy as np
import scipy.optimize as sc
import plotly.offline as pyo

pyo.init_notebook_mode(connected=True)

def powerlaw(x, c, alpha):
    return c * x ** (-alpha)

def lognormal(x, c, logmc, sigma):
    return c * np.e ** (-(np.log10(x) - logmc) ** 2 / (2 * sigma ** 2))

def lognormal_and_powerlaw(x, c, logmc, sigma, alpha):
    return np.piecewise(x, [x < 1, x >= 1], [
        lambda x: c * np.e ** (-(np.log10(x) - logmc) ** 2 / (2 * sigma ** 2)), 
        lambda x: (c * np.e ** (-(logmc ** 2) / (2 * sigma ** 2))) * x ** (-alpha)
    ])

def imf_plot(request):
    if request.method == 'POST':
        try:
            form = IMFPlotForm(request.POST, request.FILES)
            if form.is_valid():
                uploaded_file = form.cleaned_data['uploaded_file'].file
                mass_column = form.cleaned_data['mass_column']
                log_scale = form.cleaned_data.get('log_scale', False)
                df = pd.read_csv(uploaded_file)

                if not log_scale:
                    df[mass_column] = np.log10(df[mass_column])
                    print(df[mass_column])  

                bins = np.arange(-3, 2, 0.1)
                hist_data = np.histogram(df[mass_column], bins=bins)
                mass_function_data = [hist_data[0], 0.5 * (hist_data[1][1:] + hist_data[1][:-1])]

                xdata = mass_function_data[1]
                ydata = mass_function_data[0]
                mask = xdata > 0

                salpeter = sc.curve_fit(powerlaw, 10 ** xdata[mask], ydata[mask])
                lognorm = sc.curve_fit(lognormal, 10 ** xdata, ydata)
                chabrier = sc.curve_fit(lognormal_and_powerlaw, 10 ** xdata, ydata)

                dt_fit = {
                    'Data': mass_function_data,
                    'Salpeter': salpeter,
                    'Lognormal': lognorm,
                    'Chabrier': chabrier,
                }

                buttons = []
                annotations = []
                i = 0

                default_option = {'label': 'Select parametrization', 'method': 'update', 'args': [{'visible': [True] + [False] * (len(dt_fit) - 1)}, {'annotations': [dict(x=0.5, y=1.05, xref='paper', yref='paper', text='', bgcolor='white', showarrow=False, font=dict(size=12))]}]}
                buttons.append(default_option)

                fig = go.Figure()

                fig.add_trace(go.Scatter(
                    x=xdata,
                    y=ydata,
                    mode='markers',
                    name='Data',
                    marker=dict(size=8, color=xdata, colorscale='Rainbow', symbol='hexagram', showscale=False, reversescale=True),
                    error_y=dict(type='data', array=np.sqrt(ydata), visible=True)
                ))

                for name, fits in dt_fit.items():
                    if name == 'Data':
                        continue

                    if name == 'Salpeter':
                        fit_y = powerlaw(10**xdata, *fits[0])
                        label = f'{name}:$$c={fits[0][0]:.2e},~~\\alpha={fits[0][1]:.2f}$$'
                    elif name == 'Lognormal':
                        fit_y = lognormal(10 ** xdata, *fits[0])
                        label = f'{name}:$$c={fits[0][0]:.2e},~~\\log(mc)={fits[0][1]:.2f},~~\\sigma={fits[0][2]:.2f}$$'
                    elif name == 'Chabrier':
                        fit_y = lognormal_and_powerlaw(10 ** xdata, *fits[0])
                        label = f'{name}:$$c={fits[0][0]:.2e},~~\\log(mc)={fits[0][1]:.2f},~~\\sigma={fits[0][2]:.2f},~~\\alpha={fits[0][3]:.2f}$$'

                    fig.add_trace(go.Scatter(
                        x=xdata,
                        y=fit_y,
                        mode='lines',
                        line_color='black',
                        name=name,
                        visible=False
                    ))

                    visibility_list = [True] + [False] * (len(dt_fit) - 1)
                    visibility_list[i+1] = True
                    buttons.append(dict(
                        label=name,
                        method='update',
                        args=[{'visible': visibility_list},
                              {'annotations': [dict(x=0.56, y=1.055, xref='paper', yref='paper', text=label, bgcolor = 'white',showarrow=False, font=dict(size=16))]}
                              ]
                    ))
                    i += 1

                fig.data[0].visible = True
                fig.update_xaxes(mirror=True,
                                ticks='outside',
                                showline=True,
                                linecolor='black',
                                gridcolor='lightgrey'
                                )
                fig.update_yaxes(type='log',
                                 mirror=True,
                                ticks='outside',
                                showline=True,
                                linecolor='black',
                                gridcolor='lightgrey'
                                 )
                fig.update_layout(plot_bgcolor='white',
                    updatemenus=[
                        dict(
                            type='dropdown',
                            direction='down',
                            x=0.99,
                            y=0.99,
                            xanchor = 'right',
                            yanchor = 'top',
                            buttons=buttons
                        )
                    ],
                    title={
                        'text':f'IMF parameters:',
                        'y':0.89,
                        'x':0.1,
                        'xanchor':'left',
                        'yanchor':'top',
                            },
                    xaxis_title='$$\\log(M/M_{\\odot})$$',
                    yaxis_title='$$\\log(N)$$',
                    height=700,
                    width=900,
                    legend=dict(
                        x=1.05,
                        y=1,
                        traceorder='normal',
                        font=dict(
                            family='sans-serif',
                            size=12,
                            color='black'
                        ),
                    ),
                )

                plot_div = fig.to_html(full_html=False)

                # Save the data to session for later use
                request.session['plot_data'] = {
                    'xdata': xdata.tolist(),
                    'ydata': ydata.tolist(),
                    'parameters': {
                        'Salpeter': salpeter[0].tolist(),
                        'Lognormal': lognorm[0].tolist(),
                        'Chabrier': chabrier[0].tolist(),
                    }
                }

                context = {'form': form, 'plot_div': plot_div}
                return render(request, 'imf_plotter/imf_plot.html', context)
        
        except Exception as e:
            import traceback
            error_msg = f"Error processing the file: {e}\n{traceback.format_exc()}"
            return render(request, 'imf_plotter/error.html', {'error': error_msg})
    else:
        form = IMFPlotForm()

    return render(request, 'imf_plotter/imf_plot.html', {'form': form})

def data_download(request):
    plot_data = request.session.get('plot_data', None)
    if not plot_data:
        return HttpResponse('No data available for download.', status=400)

    xdata = plot_data['xdata']
    ydata = plot_data['ydata']

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="param_and_data.csv"'

    writer = csv.writer(response)
    writer.writerow(['Parametrization', 'c', 'alpha', 'sigma', 'logmc'])
    writer.writerow(['Salpeter'] + plot_data['parameters']['Salpeter'])
    writer.writerow(['Lognormal'] + plot_data['parameters']['Lognormal'])
    writer.writerow(['Chabrier'] + plot_data['parameters']['Chabrier'])
   
    writer.writerow(['m/m_sun', 'n'])
    writer.writerows(zip(xdata, ydata))
    
    return response

astroplotter/imf_plotter/templates/imf_plotter/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <title>Error</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            min-height: 100vh;
            background-color: #f8f9fa;
            margin: 0;
        }

        .container {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
            max-width: 800px;
            width: 100%;
        }

        h1 {
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Error</h1>
        <p>{{ error }}</p>
        <a href="/imf-plotter/plot-cmd/" class="btn btn-secondary">Go back</a>
    </div>
</body>
</html>

astroplotter/imf_plotter/templates/imf_plotter/imf_plot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <title>IMF Plot</title>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML"></script>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
        }
        .container {
            max-width: 1000px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
        form p {
            text-align: center;
            font-size: 14px;
            color: #555;
        }
        .load-button {
            display: inline-block;
            width: auto;
            text-align: center;
            background-color: #007bff;
            color: white;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin-left: 10px;
        }
        .load-button:hover {
            background-color: #0056b3;
        }
        .form-group {
            margin-top: 15px;
        }
        .plotly-graph-div {
            border: none; /* Remove border */
            border-radius: 0; /* Remove border-radius */
            padding: 0; /* Remove padding if needed */
            margin-top: 1px;
            display: flex;
            justify-content: center;
        }
        .plotly-graph-div > div {
            width: 100%;
            max-width: 100%;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>IMF Plot</h2>

        <form method="post" enctype="multipart/form-data">
            <p>Please keep in mind that you must provide the mass in logarithmic scale, otherwise it will overflow!</p>
            {% csrf_token %}

            <div class="form-group row align-items-center">
                <div class="col">
                    {{ form.uploaded_file.label_tag }}
                    {{ form.uploaded_file }}
                </div>
                <div class="col-auto">
                    <button type="submit" name="load_columns" class="load-button">Load Columns</button>
                </div>
                <div>
                    {{ form.log_scale }}
                    {{ form.log_scale.label_tag }}
                </div>   
            </div>

            <div class="form-group mt-3">
                {{ form.mass_column.label_tag }}
                {{ form.mass_column }}
            </div>
            <div class="form-group">
                {{ form.log_x_axis.label_tag }}{{ form.log_x_axis }}
            </div>
            <div class="form-group">
                {{ form.log_y_axis.label_tag }}{{ form.log_y_axis }}
            </div>

            <div class="text-center mt-3">
                <button type="submit" class="btn btn-primary">Generate Plot</button>
            </div>
        </form>

        {% if plot_div %}
            <div class="plotly-graph-div">
                <div>{{ plot_div|safe }}</div>
            </div>
            <div class="text-center mt-3">
                <a href="{% url 'imf_plotter:data_download' %}" class="btn btn-success">Download Data as CSV</a>
            </div>
        {% endif %}

        <div class="text-center mt-3">
            <a href="{% url 'home' %}" class="btn btn-secondary">Go back to home</a>
        </div>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
        });
    </script>
</body>
</html>